"use server";

import crypto from "node:crypto";
import bcrypt from "bcryptjs";
import { revalidatePath } from "next/cache";

import { recordAudit } from "@/lib/audit";
import { tenantDb } from "@/lib/tenant/scoped-db";
import { requireRole } from "@/lib/auth";
import { isValidRussianPhone, normalizePhone } from "@/lib/utils";
import { sendSms } from "@/lib/sms";
import { isAllowedRole, type AllowedRole } from "@/lib/roles";
import { resetEmailVerificationOnChange } from "@/lib/email-verification/core";

const NAME_MAX = 120;
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const PASSWORD_ALPHABET = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789";

function isUniqueViolation(err: unknown): boolean {
  if (!(err instanceof Error)) return false;
  if (err.message.includes("Unique constraint")) return true;
  if ("code" in err && (err as { code?: string }).code === "P2002") return true;
  return false;
}

function generateTempPassword(): string {
  const out: string[] = [];
  for (let i = 0; i < 10; i++) {
    out.push(PASSWORD_ALPHABET[crypto.randomInt(PASSWORD_ALPHABET.length)]);
  }
  return out.join("");
}

type Ok<T extends object = object> = { ok: true } & T;
type Fail = { ok: false; error: string };



/**
 * Create an account from the admin panel.
 *
 * ADMIN only: creating a user is granting access, and the role is chosen right
 * here. The password is generated, never typed — an operator inventing one
 * would reuse it, and nobody needs to know a password they are about to hand
 * over anyway. It is shown once and sent by SMS, like a reset.
 *
 * `isTempPassword` stays FALSE. Despite the name it does not mean "temporary":
 * per the schema it marks a hash produced by the guest booking flow that the
 * person does not know, and `login.ts` refuses any login while it is set.
 * Setting it here would hand out a password that cannot be used.
 */
export async function createUser(
  _prev: (Ok<{ tempPassword: string; userId: string }> | Fail) | null,
  formData: FormData,
): Promise<Ok<{ tempPassword: string; userId: string }> | Fail> {
  // Через шов изоляции: арендатор проставляется в данные и в условие.
  const db = await tenantDb();
  const session = await requireRole(["ADMIN"]);

  const name = ((formData.get("name") as string | null) ?? "").trim();
  const email = ((formData.get("email") as string | null) ?? "").trim().toLowerCase();
  const phoneRaw = ((formData.get("phone") as string | null) ?? "").trim();
  const permissionRole = ((formData.get("permissionRole") as string | null) ?? "CLIENT").trim();
  const isCustomer = formData.get("isCustomer") === "on";
  const isMaster = formData.get("isMaster") === "on";

  if (!name) return { ok: false, error: "Укажите имя" };
  if (name.length > NAME_MAX) return { ok: false, error: "Слишком длинное имя" };
  if (!EMAIL_RE.test(email)) return { ok: false, error: "Некорректный email" };
  const phone = normalizePhone(phoneRaw);
  if (!isValidRussianPhone(phone)) return { ok: false, error: "Некорректный телефон" };
  if (!isAllowedRole(permissionRole)) return { ok: false, error: "Неизвестная роль" };
  const tempPassword = generateTempPassword();

  let userId: string;
  try {
    const created = (await db.user.create({
      data: {
        name,
        email,
        phone,
        // NONE means "no login at all", so giving it a hash would be a lie the
        // login page then refuses anyway.
        passwordHash: permissionRole === "NONE" ? null : await bcrypt.hash(tempPassword, 10),
        isTempPassword: false,
        permissionRole: permissionRole as AllowedRole,
        isCustomer,
        isMaster,
      },
      select: { id: true },
    })) as { id: string };
    userId = created.id;
  } catch (err) {
    if (isUniqueViolation(err)) {
      return { ok: false, error: "Пользователь с таким email или телефоном уже существует" };
    }
    throw err;
  }

  await recordAudit({
    actor: session,
    action: "user.create",
    targetType: "User",
    targetId: userId,
    targetLabel: name,
    metadata: { role: permissionRole, isCustomer, isMaster },
  });

  if (permissionRole !== "NONE") {
    // Best effort: a failed SMS must not undo an account that already exists —
    // the password is on screen either way.
    try {
      await sendSms(phone, `Доступ в Гелеотеку: ${email} / ${tempPassword}`);
    } catch {
      // проглатываем: пароль показан администратору
    }
  }

  revalidatePath("/admin/users");
  revalidatePath("/admin/customers");
  return { ok: true, tempPassword, userId };
}

/**
 * Reset a user's password to a fresh 10-char temp string, returned to the admin
 * and sent by SMS. ADMIN/MANAGER only.
 *
 * `isTempPassword` is deliberately set to FALSE. It does not mean "this
 * password is temporary" — per the schema it means "the hash was generated by
 * the guest booking/cart flow and the user does not know it", and `login.ts`
 * refuses any login while it is set. Marking a freshly issued password with it
 * meant the manager handed the customer a password that could not be used and
 * got "Пароль не задан" instead. The password produced here IS known to the
 * user, so the flag does not apply.
 */
export async function resetUserPassword(
  userId: string,
): Promise<Ok<{ tempPassword: string }> | Fail> {
  // Через шов изоляции: арендатор проставляется в данные и в условие.
  const db = await tenantDb();
  const session = await requireRole(["ADMIN", "MANAGER"]);

  const user = (await db.user.findUnique({
    where: { id: userId },
    select: { phone: true, name: true, permissionRole: true },
  })) as { phone: string; name: string; permissionRole: string } | null;
  if (!user) return { ok: false, error: "Пользователь не найден" };
  if (user.permissionRole === "NONE") {
    return {
      ok: false,
      error: "Эта учётная запись не может выполнять вход (роль NONE)",
    };
  }

  const tempPassword = generateTempPassword();
  const passwordHash = await bcrypt.hash(tempPassword, 12);

  await db.user.update({
    where: { id: userId },
    data: { passwordHash, isTempPassword: false },
  });

  // Fire-and-log SMS — failure shouldn't block the admin getting the
  // temp password back, since they need to communicate it themselves
  // if SMS provider is down.
  void sendSms(
    user.phone,
    `Geleoteka: Ваш временный пароль ${tempPassword}. Войдите и смените его в личном кабинете.`,
  ).catch((err) => console.error("[reset-password sms]", err));

  await recordAudit({
    actor: session,
    action: "user.password_reset",
    targetType: "User",
    targetId: userId,
    targetLabel: user.name,
  });

  revalidatePath(`/admin/customers/${userId}`);
  revalidatePath(`/admin/team/${userId}`);
  revalidatePath(`/admin/users/${userId}`);
  revalidatePath("/admin/users");
  // The roles page counts holders per role, and the sidebar is built from the
  // viewer's permissions — both go stale on a role change. Missing these is why
  // promoting somebody to admin left the roles page showing the old picture.
  revalidatePath("/admin/roles");
  revalidatePath("/admin", "layout");
  return { ok: true, tempPassword };
}

/**
 * Edit user contact triple (name/email/phone). Used for any user role.
 * Validates phone (RU format) and email (basic regex). Returns ok or
 * collision error. ADMIN/MANAGER only.
 */
export async function updateUserContacts(
  userId: string,
  input: { name: string; email: string; phone: string },
): Promise<Ok | Fail> {
  // Через шов изоляции: арендатор проставляется в данные и в условие.
  const db = await tenantDb();
  await requireRole(["ADMIN", "MANAGER"]);

  const name = input.name.trim();
  const email = input.email.trim().toLowerCase();
  const phone = normalizePhone(input.phone.trim());

  if (!name || name.length > NAME_MAX) {
    return { ok: false, error: "Имя обязательно (до 120 символов)" };
  }
  if (!email || !EMAIL_RE.test(email)) {
    return { ok: false, error: "Некорректный email" };
  }
  if (!isValidRussianPhone(phone)) {
    return {
      ok: false,
      error: "Телефон должен быть в формате +7XXXXXXXXXX или 8XXXXXXXXXX",
    };
  }

  const current = (await db.user.findUnique({
    where: { id: userId },
    select: { email: true },
  })) as { email: string } | null;
  if (!current) return { ok: false, error: "Пользователь не найден" };

  try {
    await db.user.update({
      where: { id: userId },
      data: {
        name,
        email,
        phone,
        ...resetEmailVerificationOnChange(current.email, email),
      },
    });
  } catch (err) {
    if (isUniqueViolation(err)) {
      return {
        ok: false,
        error: "Email или телефон уже используются другим пользователем",
      };
    }
    throw err;
  }

  revalidatePath(`/admin/customers/${userId}`);
  revalidatePath(`/admin/team/${userId}`);
  revalidatePath(`/admin/users/${userId}`);
  revalidatePath("/admin/users");
  // The roles page counts holders per role, and the sidebar is built from the
  // viewer's permissions — both go stale on a role change. Missing these is why
  // promoting somebody to admin left the roles page showing the old picture.
  revalidatePath("/admin/roles");
  revalidatePath("/admin", "layout");
  return { ok: true };
}

/**
 * Change a user's permissionRole. ADMIN-only — managers must not be
 * able to elevate themselves or others. Refuses to demote the last
 * remaining ADMIN to prevent locking the org out.
 */
export async function changeUserRole(
  userId: string,
  newRole: string,
): Promise<Ok | Fail> {
  // Через шов изоляции: арендатор проставляется в данные и в условие.
  const db = await tenantDb();
  const session = await requireRole(["ADMIN"]);

  if (!isAllowedRole(newRole)) {
    return { ok: false, error: "Неизвестная роль" };
  }

  const user = (await db.user.findUnique({
    where: { id: userId },
    select: { permissionRole: true, name: true },
  })) as { permissionRole: string; name: string } | null;
  if (!user) return { ok: false, error: "Пользователь не найден" };

  // Last-admin guard: refuse to demote the only ADMIN to anything else.
  if (user.permissionRole === "ADMIN" && newRole !== "ADMIN") {
    const adminCount = await db.user.count({ where: { permissionRole: "ADMIN" } });
    if (adminCount <= 1) {
      return {
        ok: false,
        error: "Нельзя понизить последнего администратора — назначьте сначала другого",
      };
    }
  }

  // Self-demotion guard: prevent admin from accidentally demoting themselves.
  if (session.id === userId && newRole !== "ADMIN") {
    return {
      ok: false,
      error: "Нельзя изменить свою роль — попросите другого администратора",
    };
  }

  await db.user.update({
    where: { id: userId },
    data: { permissionRole: newRole as AllowedRole },
  });

  // After the guards, not before: a refused demotion is not a role change, and
  // the log must not claim one happened.
  await recordAudit({
    actor: session,
    action: "user.role_change",
    targetType: "User",
    targetId: userId,
    targetLabel: user.name,
    metadata: { from: user.permissionRole, to: newRole },
  });

  revalidatePath(`/admin/customers/${userId}`);
  revalidatePath(`/admin/team/${userId}`);
  revalidatePath(`/admin/users/${userId}`);
  revalidatePath("/admin/users");
  // The roles page counts holders per role, and the sidebar is built from the
  // viewer's permissions — both go stale on a role change. Missing these is why
  // promoting somebody to admin left the roles page showing the old picture.
  revalidatePath("/admin/roles");
  revalidatePath("/admin", "layout");
  return { ok: true };
}

/**
 * Disable login for a user by setting permissionRole=NONE and clearing
 * the password hash. Reversible only by changeUserRole back to a real
 * role + resetUserPassword. ADMIN-only with the same self-protection
 * and last-admin guards as changeUserRole.
 */
export async function setUserDisabled(
  userId: string,
  disabled: boolean,
): Promise<Ok | Fail> {
  // Через шов изоляции: арендатор проставляется в данные и в условие.
  const db = await tenantDb();
  const session = await requireRole(["ADMIN"]);

  if (session.id === userId && disabled) {
    return { ok: false, error: "Нельзя заблокировать свой аккаунт" };
  }

  // Read once, before the branch: the name is needed for the audit entry on
  // either path, and the block branch needs the role anyway.
  const target = (await db.user.findUnique({
    where: { id: userId },
    select: { name: true, permissionRole: true },
  })) as { name: string; permissionRole: string } | null;
  if (!target) return { ok: false, error: "Пользователь не найден" };

  if (disabled) {
    if (target.permissionRole === "ADMIN") {
      const adminCount = await db.user.count({
        where: { permissionRole: "ADMIN" },
      });
      if (adminCount <= 1) {
        return {
          ok: false,
          error: "Нельзя заблокировать последнего администратора",
        };
      }
    }
    await db.user.update({
      where: { id: userId },
      data: { permissionRole: "NONE", passwordHash: null, isTempPassword: false },
    });
  } else {
    // Restoring access — give CLIENT role by default. Admin can elevate
    // afterwards via changeUserRole. Caller should follow up with
    // resetUserPassword to give the user a working credential.
    await db.user.update({
      where: { id: userId },
      data: { permissionRole: "CLIENT" },
    });
  }

  await recordAudit({
    actor: session,
    action: "user.block",
    targetType: "User",
    targetId: userId,
    targetLabel: target.name,
    // Unblocking is the same event with the opposite answer — one action with a
    // flag reads better in the log than two verbs that must be kept in sync.
    metadata: { disabled },
  });

  revalidatePath(`/admin/customers/${userId}`);
  revalidatePath(`/admin/team/${userId}`);
  revalidatePath(`/admin/users/${userId}`);
  revalidatePath("/admin/users");
  // The roles page counts holders per role, and the sidebar is built from the
  // viewer's permissions — both go stale on a role change. Missing these is why
  // promoting somebody to admin left the roles page showing the old picture.
  revalidatePath("/admin/roles");
  revalidatePath("/admin", "layout");
  return { ok: true };
}
